services:

  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # redirection http -> https (global)
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # provider fichier pour le TLS local
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      # dashboard local (HTTP) + metriques
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addrouterslabels=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/certs:/certs:ro
      - ./reverse-proxy/dynamic:/dynamic:ro
    networks:
      - transcendance_net

  # gateway:
  #   container_name: gateway
  #   build:
  #     context: ./server/gateway
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./server/gateway:/app
  #   env_file:
  #     - ./.env
  #   environment:
  #     CLIENT_ID: ${CLIENT_ID}
  #     CLIENT_SECRET: ${CLIENT_SECRET}
  #     REDIRECT_URI: ${REDIRECT_URI}
  #     CHOKIDAR_USEPOLLING: true
  #   depends_on:
  #     - auth


  auth:
    container_name: auth
    build:
      context: ./server/services/auth
    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.priority=20"
      - "traefik.http.services.auth.loadbalancer.server.port=3001"
    volumes:
      - ./server/services/auth:/app
    env_file:
      - ./.env
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      CHOKIDAR_USEPOLLING: true
    networks: 
      - transcendance_net

  webapp:
    container_name: webapp
    build:
      context: ./webapp
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/webapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`localhost`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.priority=1"
      - "traefik.http.services.front.loadbalancer.server.port=5173"
    networks:
    - transcendance_net

  # adminer:
  #   image: adminer:4.8.1-standalone
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./server/prisma:/var/sqlite

  # server:
  #   container_name: server
  #   build:
  #     context: ./server
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./server:/server
  #     - ./server/prisma:/server/prisma
  #   env_file:
  #     - ./.env
  #   environment:
  #     DATABASE_URL: "file:/server/prisma/dev.db"
  #     CLIENT_ID: ${CLIENT_ID}
  #     CLIENT_SECRET: ${CLIENT_SECRET}
  #     REDIRECT_URI: ${REDIRECT_URI}
  #     CHOKIDAR_USEPOLLING: true

networks:
  transcendance_net:
    driver: bridge
